dataset_root: "C:/Users/Can Tekin/Desktop/Endüstriyel Uygulamalarda Yapay Zeka Projesi"
cs2_cycling_dir: "main/CS2_3"
ocv_init_capacity_dir: "OCV + Initial Capacity"
ocv_soc_dir: "OCV-SOC"
high_current_dir: "Yüksek akım stresi"
dst_fuds_dir: "Dynamic Driving Profiles"
cache_dir: "data_cache"
models_dir: "models"
logs_dir: "logs"
